Use new chezmoi url as per documentation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,27 +1,26 @@
 #!/bin/sh
 
-# -e: exit on error
-# -u: exit on unset variables
-set -eu
+set -eu # exit on Error and Unset variables
 
 if ! chezmoi="$(command -v chezmoi)"; then
-  bin_dir="${HOME}/.local/bin"
-  chezmoi="${bin_dir}/chezmoi"
-  echo "Installing chezmoi to '${chezmoi}'" >&2
-  if command -v curl >/dev/null; then
-    chezmoi_install_script="$(curl -fsSL https://chezmoi.io/get)"
-  elif command -v wget >/dev/null; then
-    chezmoi_install_script="$(wget -qO- https://chezmoi.io/get)"
-  else
-    echo "To install chezmoi, you must have curl or wget installed." >&2
-    exit 1
-  fi
-  sh -c "${chezmoi_install_script}" -- -b "${bin_dir}"
-  unset chezmoi_install_script bin_dir
+    chezmoi_url="get.chezmoi.io/lb"
+    chezmoi="${HOME}/.local/bin/chezmoi"
+    echo "Installing chezmoi to '${chezmoi}'" >&2
+
+    if command -v curl >/dev/null; then
+        chezmoi_install_script="$(curl -fsSL $chezmoi_url)"
+    elif command -v wget >/dev/null; then
+        chezmoi_install_script="$(wget -qO- $chezmoi_url)"
+    else
+        echo "To install chezmoi, you must have curl or wget installed." >&2
+        exit 1
+    fi
+
+    sh -c "${chezmoi_install_script}"
+    unset chezmoi_install_script chezmoi_url
 fi
 
 set -- init --apply iliqiliev
 
 echo "Running 'chezmoi $*'" >&2
-# exec: replace current process with chezmoi
-exec "$chezmoi" "$@"
+exec "$chezmoi" "$@" # exec: replace current process with chezmoi
